server:
  port: 80

spring:
  application:
    name: yzs-consumer
  profiles:
    #引入application-common.yml
    include: common

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    #是否从注册中心抓取信息,默认为true,集群必须配置才能使用ribbon负载均衡
    fetch-registry: true
    #是否注册
    register-with-eureka: true