server:
  port: 7001

spring:
  application:
    name: yzs-eureka-server
  profiles:
    #引入application-common.ymls
    include: common

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false

